### ISSUE TITLE
Sample placement lost between steps

### ISSUE THREAD

**Issue by KarinSollander** [Clinical-Genomics/clinical_EPPs#101]
Lims Issue
---------------

**Work Flow:** CG003 WGS PCR free
**Protocol:** CG002 TruSeq DNA PCR-free Library Prep
**Step:** CG002 - End repair Size select

**Description:**

Samples, from both tubes and plate, were placed in a plate in step CG002 - Aliquot Samples for Covaris.
https://clinical-lims.scilifelab.se/clarity/work-complete/116668

In next step, CG002 - Fragment DNA (TruSeq DNA), it looks like they have been placed in tubes.
https://clinical-lims.scilifelab.se/clarity/work-complete/116669

This leads to the samples ending up in tubes in the following steps sample placement CG002 - End repair Size select 
https://clinical-lims.scilifelab.se/clarity/work-placement/116697

This makes it hard to sort the samples since there is no reference to previous steps.

**Comment by mayabrandi** [comment]
We solved this together.
