### ISSUE TITLE
Adding sample info 

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/clinical_EPPs#107]
Lims Issue
---------------

**Work Flow:** TWIST v2
**Protocol:** Target Enrichment TWIST v1
**Step:** Hybridize Library TWIST

**Description:** When choosing a pool in the above step (see picture 1 marked in red), all samples in that pool will pop-up (see picture 2). I would like to add an extra column where the LIMS-IDs are visible (see the green box in picture 2). 

<img width="180" alt="Picture1" src="https://user-images.githubusercontent.com/26735714/67565691-53e75c00-f726-11e9-84bb-7a99254a22cb.png">
<img width="717" alt="Picture2" src="https://user-images.githubusercontent.com/26735714/67565693-53e75c00-f726-11e9-81a8-391b8e9f88fb.png">

**Comment by mayabrandi** [comment]
Im quite sure, what you are asking for is not supported atm. Im sending an issue to genologics, asking if they would consider implementing the feature.

**Comment by mayabrandi** [comment]
Genologigs will look into adding the requested feature in the future
