### ISSUE TITLE
Add a limit for maximum volume in the pooling script

### ISSUE THREAD

**Issue by annagellerbring** [Clinical-Genomics/clinical_EPPs#123]
Lims Issue
---------------

**Work Flow:** TWISTv2
**Protocol:** Target Enrichment TWIST v1
**Step:** Pool samples for hybridization TWIST

**Description:** Add rule in the script that the total volume that can be added of each sample is 17 ul or less. If a higher volume is needed of a sample, give a warning!

**Comment by mayabrandi** [comment]
issue solved. closing
