### ISSUE TITLE
Modify calculation for Genotyping workflow

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/clinical_EPPs#125]
Lims Issue
---------------

**Work Flow:** CG001 - Genotyping
**Protocol:** CG002 - Genotyping
**Step:** CG002 - Plate Setup MAF

**Description:** We would like to to modify the calculations of the script. Instead of having a fixed final volume, we would like to have a fixed sample volume. 

**Basic requirement from MAF in Hudding:**
MAF requirements: 4 ng/ul final concentration of sample in minimum 15 ul volume, no maximum volume.

**Script details:**
- Maximum volume the BRAVO can pipette is 180 ul. This means that the highest concentration of sample that can be used in combination with a sample volume of 3 ul is 244 ng/ul ((4*(180+3))/3).

- For samples with a concentration of 244 ng/ul or higher, the script should adjust the the sample volume (decrease it to first 2, then 1, then 0.5 ul). Minimum sample volume is 0.5 ul. This means that sample concentrations up to 1444 ng/ul can be included, but for sample concentrations between 244-1444 ng/ul the sample volume will be less than 3 ul.

-> 20-244 ng/ul: sample volume 3 ul 
-> 244-364 ng/ul: sample volume 2 ul 
-> 364-724 ng/ul: sample volume 1 ul
-> 724-1444 ng/ul: sample volume 0.5 ul

- The minimum concentration possible to pipette with 3 ul sample is 20 ng/ul. If sample is lower than 20 ng/ul, the script should increase (double?) the sample + water volume so that a minimum total volume of 15 ul is aquired.

- All water volumes should be pipetted with the same file structure that is used for the current microbial workflow (csv file)

- We need a file or pipetting scheme (Placement map) with very very clear instructions/information on how much the sample volume is. We don't need to know the 3 ul so clearly, but it has to be very very clear which wells have a different volume and what that volume is.

**Comment by annaengstrom** [comment]
We can discuss this more in detail, and I can explain more clearly when we meet next week

**Comment by mayabrandi** [comment]
We have gone through this today, and I have updated the scripts. I will deploy them in production as soon as you have finished the samples you are working on atm @annaengstrom . Let we know when you are don. Then we can close this issue.

**Comment by annaengstrom** [comment]
Done.

**Comment by mayabrandi** [comment]
I have updated production with the updated scripts. Closing this issue now

**Comment by annaengstrom** [comment]
Two things missing in production view:

- QC flags
- script to create csv file for water volume only (should be the same for the microbial workflow). One file per plate.

**Comment by annaengstrom** [comment]
> Two things missing in production view:
> 
> * [ ]  QC flags
> * [ ]  script to create csv file for water volume only (should be the same for the microbial workflow). One file per plate.

Has this been fixed @mayabrandi ?

**Comment by mayabrandi** [comment]
I will open a separate issue for this @annaengstrom. I need a minute of your time to specify what the csv should look like.

**Comment by annaengstrom** [comment]
I have used the script, CSV file works fine, but calculations for sample concentrations below 5 ng/ul does not seem to be correct. Since the minimum concentration needed is 4 ul, the script should give an output of no value at all for samples with a concentration below 4 ng/ul (and should color those squares red in the sample placement map), but it seems 5 is a limit? A concentration of 4 and over is actually fine for this step, but when I try concentrations below 5, the calculations does not seems to be correct.

**Comment by mayabrandi** [comment]
Lets look at it together tomorrow?

**Comment by annaengstrom** [comment]
Are the last steps deployed in production?

**Comment by annaengstrom** [comment]
Done.
