### ISSUE TITLE
Add existing script to a new step in the WGS workflow

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/clinical_EPPs#127]
Lims Issue
---------------

**Work Flow:** WGS PCR free v4
**Protocol:** TruSeq DNA PCR free library prep
**Step:** Aliquot samples for Covaris

**Description:** 

Could you please add a script/button for "Create csv file for buffer volumes" - meaning the exact same script used in the microbial workflow should be used, to put the buffer volumes in a csv file.

 it should be done in the same way it is in Microbial WGS v5/Nextera Microbial WGS v4/Normalization of microbial samples v2

**Comment by mayabrandi** [comment]
@annaengstrom I need to know where in the microbial workflow the script that you are referring to, is used!

**Comment by mayabrandi** [comment]
@annaengstrom This issue looks lie the same one as [this one](https://github.com/Clinical-Genomics/clinical_EPPs/issues/130) True?

**Comment by annaengstrom** [comment]
@mayabrandi yes indeed. 10 days between opening the same issue twice... I simply did not remember I had already done it.
