### ISSUE TITLE
TWIST WF v3

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/clinical_EPPs#128]
**The new workflow is validated in AMS *2145:2*. It includes validations of issues #128 #143 and #149. In addition, all changes are documented in this validation report.** 

Lims Issue
---------------

**Work Flow:** TWIST

**Description:** Lots of changes to the TWIST WF. See this issue, #143 and #149.

Details in this document: https://docs.google.com/document/d/1n5mtPq_CNrwxbqyAhzSghHobaN0CsDdWLQ73pB4HMNA/edit?ts=5e3432bc

**Comment by annaengstrom** [comment]
I put this on hold for now. Have to schedule a time in the next few weeks.

**Comment by annaengstrom** [comment]
To do:

- Add doc 1993 to all steps in protocol “Library prep TWIST”, remove 1879 from all steps
- Never auto placement in any step, user always has to do this
- Default placement should be 96 well plate (except step for making pools - where only tube is available) and placement should be in columns not in rows. 
- Add comment field to every step
- Can we see Lims IDs in every step? Lims ID first in every step

**Comment by annaengstrom** [comment]
Would it be easier for you @mayabrandi  to add all remaining tasks here, instead of having in the Word document on Drive?
FYI @annagellerbring

**Comment by annagellerbring** [comment]
> Would it be easier for you @mayabrandi to add all remaining tasks here, instead of having in the Word document on Drive?
> FYI @annagellerbring

In that case I can add them @annaengstrom

**Comment by mayabrandi** [comment]
It doesn't really matter, but I need to go through the tasks togther with someone to make sure I understand what to do.

**Comment by annagellerbring** [comment]
Then let's not waste time to document the changes in several places. We keep it in the google doc and sit together and look at it when possible.

**Comment by cesve** [comment]
@mayabrandi 
In new TWIST wf3: In step "Buffer Exchange TWIST" Protocol "Pre Processing TWIST v1" we have a script: Calculate volumes. We would like to add calculation to the script that calculated the UDF "Volume Elution (ul)":

"Volume Elution" = 0.8* "Sample Volume (ul)".
If "Sample Volume (ul)" < 50 --> Volume Elution = 40

**Comment by cesve** [comment]
@mayabrandi 
In new TWIST wf3: Step "Quantit QC (DNA) TWIST" i protocol "Initial QC TWIST v2". 
I "Placement map" syns fel värden i själva plate layouten. Man vill ha Source container och Source Well inte Original cont. och original well.

Jämför dessa två:

file:///Users/cecilia.svensson/Downloads/92-961667.html

file:///Users/cecilia.svensson/Downloads/92-961469.html

**Comment by cesve** [comment]
@mayabrandi 
In new TWIST v3: in protocol "Library Prep TWIST v2" and step "Aliquot samples for enzymatic fragmentation TWIST" we would also like to add a script that creates a file with volumes. The file is the same as the one created in wf "Microbial WGS" protocol "Nextera microbial WGS" step "Normalization of microbial samples".

Two separate files are generated. One with buffer volumes and one with sample volumes.

**Comment by cesve** [comment]
@mayabrandi 
In new TWIST v3: in protocol "Initial QC TWIST v2" "Step: Quantit QC (DNA) TWIST" and step "Qubit QC (DNA) TWIST". Add a script that sets QC-flags:

Suggestion for script:
If amount >= 250 **& if** 500 <= c >= 8.33 ng/ul → Passed
If amount 100 <= x < 250 **& if** 100 ng/ul >=c >= 1.66 → Passed
If amount <100 → Fail (perhaps we can skip this?)
If else → Fail

**Comment by mayabrandi** [comment]
**Work Flow:** TWIST v2
**Protocol:** Target Enrichment TWIST v1
**Step:** Pool samples for hybridization TWIST

- [ ] **Description:** Updating script for calculating volumes to pool with requirements:
- minimum input amount to pool: 187.5ng
- if input amount to pool is <187.5ng give error message that explains that the pool contains too many samples, and that a sample needs to be removed from the pool

Also investigate: what criteria are giving red QC-flag now? We got red flag for pool D1 and F1 in tga200423 but couldn't understand why (https://clinical-lims.scilifelab.se/clarity/work-complete/142925)

**Comment by cesve** [comment]
Verification
Planned by: CS and MB

Protocol/step | Test Specification | Pass/Fail | Comments
-- | -- | -- | --
Initial QC TWIST v2 |   |   |  
Tape | Add 8 samples to the step. Set arrived date and run the scripts "Set missing reads" and "Set received date" Choose "Skip buffer exchange for 4 samples. |   |  
Pre Processing TWIST v1 |   |   |  
Reception Control TWIST |   |   |  
Library Prep TWIST v2 |   |   |  
Step 1. Aliquot samples for enzymatic fragmentation TWIST | Add 16 samples to the step. Samples with different "Amount" (=x) will be chosen. x<=10ng, 10ng<=x<=50ng, 50ng<=x<=250ng and x>=250ng. One sample will have x=0ng. 8 samples will be passed on to Step 2, Enzymatic fragmentation and 8 samples will be passed on to Step 3 KAPA library preparation |   | Run all 3 scripts in this step. Make sure that the scripts works as expected. See that the amount needed is correct. Check that the placement map is correct. Make sure that the 16 samples are passed to the correct step (step 2 or step 3).
Step 2. Enzymatic fragmentation TWIST | Place the samples in 96 well plate. |   | Make sure that the script that generates the file works and that the file can be used by the Hamilton software. Make sure that the file generates the correct information.
  |   |   |  
Step 1. Depends on Workflow * |   |

**Comment by cesve** [comment]
Seems like the wrong QC-flags are transferred to samples ACC6538A69 and ACC6538A93 in this step: https://clinical-lims-stage.scilifelab.se/clarity/work-details/144663

**Comment by cesve** [comment]
I also have problems with the pooling script https://clinical-lims-stage.scilifelab.se/clarity/work-details/144670

**Comment by cesve** [comment]
> **Work Flow:** TWIST v2
> **Protocol:** Target Enrichment TWIST v1
> **Step:** Pool samples for hybridization TWIST
> 
> * [x]  **Description:** Updating script for calculating volumes to pool with requirements:
> * minimum input amount to pool: 187.5ng
> * if input amount to pool is <187.5ng give error message that explains that the pool contains too many samples, and that a sample needs to be removed from the pool
> 
> Also investigate: what criteria are giving red QC-flag now? We got red flag for pool D1 and F1 in tga200423 but couldn't understand why (https://clinical-lims.scilifelab.se/clarity/work-complete/142925)
> 
> * [x]  If possible, can we sort the pools in well order in the pooling map? Like:
>   Pool #A1
>   Pool #B1
>   Pool #C1
>   We can name the pools differently if that's needed.
> 
> Can we also sort the samples in the pools by there well position:
> A:1
> B:1
> C:1
> D:1
> E:1
> F:1
> G:1
> H:1
> A:2
> B:2
> C:2 and so on.
> 
> I have implemented this. Please test it! @cesve

When having pools A1, B2 and H1 they are sorted as A1, B2, H1. But I want to sort them like A1, H1, B2. Can this be fixed @mayabrandi ?

**Comment by cesve** [comment]
Validation approved and published. Closing issue.
