### ISSUE TITLE
Add existing script to a new step

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/clinical_EPPs#130]
Lims Issue
---------------

**Work Flow:** WGS PCR free v4
**Protocol:** TruSeq DNA PCR-free Library Prep
**Step:** Aliquot Samples for Covaris

**Description:** Please add script to produce a csv file for the buffer only (water/EB), it should be done in the same way it is in Microbial WGS v5/Nextera Microbial WGS v4/Normalization of microbial samples v2

**Comment by mayabrandi** [comment]
Done
