### ISSUE TITLE
Hamilton Kapa TWIST - new csv file generation

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/clinical_EPPs#131]
Lims Issue
---------------

**Work Flow:** TWIST

**Description:** Describe issue here!!!
A new robot "Hamilton" is being implemented in production. The new robot needs a input file that should be generated by lims. At the same time we need to adjust the workflow a little.

More details will come.

**Comment by annaengstrom** [comment]
Just to check, will this be the same workflow for the manual prep? Will all steps remain as they are today?

**Comment by KarinSollander** [comment]
This is for the whole work to re-do the workflow for the automation.
