### ISSUE TITLE
Change calculation script in step "Aliquot samples for Covaris"

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#144]
Lims Issue
---------------

**Work Flow:** WGS PCR-free v4
**Protocol:** TruSeq DNA PCR-free Library Prep
**Step:** Aliquot Samples for Covaris

**Description:** The script in this step calculates volumes of sample and buffer. Today the script only calculates the volumes for three fixed amounts (UDF "amount needed" with values 200, 1100 and 3000). We would like to keep the pre-sets 200 and 1100 but remove 3000 and add 100 instead. We would also like to change the script a bit so if the UDF "total amount" is less than what was chosen in UDF "amount needed" (100, 200 or 1100) it will base the calculations on the "total amount". (I.e. "amount needed"="total amount")

I think the calculation would be similiar to the one used in step "Aliquot samples for enzymatic fragmentation TWIST" in the TWIST WF.

**Comment by cesve** [comment]
MB: you don't need to start working on this issue now.

**Comment by mayabrandi** [comment]
Okej :)

> 21 apr. 2020 kl. 12:53 skrev cesve <notifications@github.com>:
> 
> MB: you don't need to start working on this issue now.
> 
>

**Comment by cesve** [comment]
Closing this issue, if needed, open a new issue in https://github.com/Clinical-Genomics/cg_lims/issues
