### ISSUE TITLE
Calculate Reads for pools in Novaseq queue

### ISSUE THREAD

**Issue by AnnaZetterlund** [Clinical-Genomics/clinical_EPPs#145]
Lims Issue
---------------

**Work Flow:** NovaSeq v2
**Protocol:** Define Run Format and Calculate Volumes (Nova Seq)
**Step:** Queue

**Description:** A script either here och somewhere else that calculate the total amount of reads for a pool that are made in the library prep. The twist samples comes in pools from the library prep but only the reads from one sample in the pool are shown here.

**Comment by mayabrandi** [comment]
Okej. Lest have a look at it together befor I start working on this. Let me know when you have time!

> 22 apr. 2020 kl. 07:34 skrev AnnaZetterlund <notifications@github.com>:
> 
> Description: A script either here och somewhere else that calculate the total amount of reads for a pool that are made in the library prep. The twist samples comes in pools from the library prep but only the reads from one sample in the pool are shown here.
> 
>

**Comment by AnnaZetterlund** [comment]
Hej, 
It seems that the calculations did not work for the pools with apptag PAN... Only for the pools started with EXO... 
Är det här skriptet apptag beroende?
