### ISSUE TITLE
Add an option in existing udf

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#150]
Lims Issue
---------------

**Work Flow:** WGS PCR free v4
**Protocol:** Library validation QC wgs v3
**Step:** CG002 - qPCR QC (Library Validation)

**Description:** In the step details and UDF "Method Document" add the option "1031". Now it's just possible to choose "1499".

**Comment by mayabrandi** [comment]
From what I can se the option is already there! 
can I close the issue? @cesve 
![Skärmavbild 2020-05-26 kl  09 00 43](https://user-images.githubusercontent.com/1306333/82869980-75fcc300-9f2f-11ea-901c-01160630d372.png)
