### ISSUE TITLE
Add sequecing method to older samples

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/clinical_EPPs#151]
Lims Issue
---------------

**Description:** 
Samples sequenced on NovaSeq before 10 mars 2020 are missing sequencing method. 

Add sequencing method 1830:4 to all samples sequenced on NovaSeq between 2019-03-25 - 2020-03-10.

**Comment by mayabrandi** [comment]
Okej. This is done now. Ill close the issue. Let me know if you need any more help with this.
