### ISSUE TITLE
Make preset required in aggregation step

### ISSUE THREAD

**Issue by KarinSollander** [Clinical-Genomics/clinical_EPPs#174]
Lims Issue
---------------

**Work Flow:** WGS PCR free v4
**Protocol:** Initial QC wgs v4
**Step:** Aggregate QC (DNA)

**Description:** The aggregation can be made without selecting a preset. This will lead to loss of information that is required in later steps. See deviation PROD #189

**Comment by cesve** [comment]
Closing as it's not relevant any more.
