### ISSUE TITLE
Faulty csv-file created by script

### ISSUE THREAD

**Issue by annagellerbring** [Clinical-Genomics/clinical_EPPs#175]
Lims Issue
---------------

**Work Flow:** TWISTv2
**Protocol:** Library prep TWIST v1
**Step:** Aliquot samples for enzymatic fragmentation TWIST

**Description:** When the script is generating the file for buffer there is an error message saying that there is wrong or blank values for some UDFs, and in the file the buffer column is only 0 for all samples. Example: https://clinical-lims.scilifelab.se/clarity/work-details/148749 (but I needed to create the file manually and upload it).

**Comment by cesve** [comment]
May be fixed in new Twist WF.

**Comment by cesve** [comment]
Done in new wf.
