### ISSUE TITLE
All 3 files created are not visible in step

### ISSUE THREAD

**Issue by annagellerbring** [Clinical-Genomics/clinical_EPPs#176]
Lims Issue
---------------

**Work Flow:** TWIST v2
**Protocol:** Library Prep TWIST v1
**Step:** Aliquot samples for enzymatic fragmentation

**Description:** In the step 3 files are created; 1 for buffer, 1 for sample and 1 placement map. But there is only 2 possible files available, so when the placement map is created, it replaces the buffer-file which is not visible anymore.

**Comment by cesve** [comment]
Needs to be fixed in existing WF.

**Comment by mayabrandi** [comment]
This should be solved now. Ill close the issue. Please re-open it if you get problems.
