### ISSUE TITLE
Aggregate DIN value

### ISSUE THREAD

**Issue by annagellerbring** [Clinical-Genomics/clinical_EPPs#177]
Lims Issue
---------------

**Work Flow:** Twist v2
**Protocol:** Initial QC TWIST v2
**Step:** Aggregate QC (DNA) TWIST

**Description:** We have started to add DIN value to some samples in Initial QC Twist v2 - Tapestation Reception control Twist. The DIN value needs to be aggregated in Aggregate QC (DNA) TWIST. It will be used later in the protocol Library prep TWIST v1 - Aliquot samples to enzymatic fragmentation Twist. I added the UDF DIN value to Tapestation Reception control Twist and to Aliquot samples to enzymatic fragmentation Twist.

**Comment by annaengstrom** [comment]
@linnealafleur

**Comment by annagellerbring** [comment]
@cesve as a UDF next to the UDF "amount needed".

**Comment by cesve** [comment]
Done in new wf.
