### ISSUE TITLE
Change placement map in Quantit QC (DNA) TWIST

### ISSUE THREAD

**Issue by linnealafleur** [Clinical-Genomics/clinical_EPPs#178]
Lims Issue
---------------

**Work Flow:** Initial QC TWIST v2
**Protocol:** Quantit QC (DNA) TWIST
**Step:** Step 1?

**Description:** In the placement map that can be generated in the Quantit protocol, in the plate view, we would like "Source container" and "Source well" to be displayed instead of "Original container" and "Original well"

**Comment by cesve** [comment]
This will be fixed in the new Twist WF. Is it really urgent or can it wait 1-2 weeks?

**Comment by linnealafleur** [comment]
Great that it gets fixed, then it can wait.

**Comment by cesve** [comment]
Perfect!
