### ISSUE TITLE
Sort values in file by sample well position

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#183]
Lims Issue
---------------

**Work Flow:** TWIST v3
**Protocol:** KAPA Library Preparation
**Step:** Enzymatic fragmentation TWIST, KAPA Library Preparation

**Description:** We recently learned that to run the KAPA method in the Hamilton software in a correct way, the file created in steps above (File for Hamilton, script EPPs/make_kapa_txt.py), needs to be sorted by **sample well**. They should be sorted as A1, B1, C1...., A2, B2, C2 etc.

**Comment by mayabrandi** [comment]
This is now implemented. See PR https://github.com/Clinical-Genomics/cg_lims/pull/4
