### ISSUE TITLE
Add limit of maximum volume of sample when pooling to hyb

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#184]
Lims Issue
---------------

**Work Flow:** TWIST v3
**Protocol:** Target enrichment TWIST
**Step:** Pool samples for hybridization TWIST

**Description:** In the the script used in workflow v2 there's a limit of 15 ul/sample when samples are pooled for hyb. When the new wf v3 was created this limit was missed but we would like to have it in the new wf v3 as well.

**Comment by mayabrandi** [comment]
Done by this pr https://github.com/Clinical-Genomics/cg_lims/pull/7
