### ISSUE TITLE
Create a new UDF "Level of multiplexing"

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#190]
Lims Issue
---------------

**Work Flow:** Twist v3
**Protocol:** Target Enrichment TWIST
**Step:** Pool samples for hybridization TWIST

**Description:** Add a UDF for “Level of multiplexing” which could be filled in through the drop down list at the top of the sample list. Values should range from 1-8. 

The UDF should be filled in, in the Reception Control TWIST step. Later in the workflow, in protocol "Target Enrichment TWIST" step "Pool samples for hybridization TWIST" this UDF with values should be visualised. It should be visualised in the "Pool samples" view.

**Comment by mayabrandi** [comment]
Done by this PR https://github.com/Clinical-Genomics/cg_lims/pull/6
