### ISSUE TITLE
Change QC-criterias in initial QC Twist

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#193]
Lims Issue
---------------

**Work Flow:** Twist v3
**Protocol:** Initial QC TWIST v3
**Step:** Qubit QC (DNA) TWIST and Quantit QC (DNA) TWIST

**Description:** Unfortunately the needs in this step have slightly changed...

We would like to change the QC-criteria to the following:

1. Calculate amount.
2. Is it possible to look at the UDF "sample source" and set the following criterias:

If "Sample Source" is other than (not equal) "cfDNA"
And if "Amount" >= 300
And if c <=250
And if c >= 8.33 ---> PASS

If "Sample Source" = "cfDNA"
And if "Amount" >= 10
And if "Concentration" <= 250
And if c >= 0.2 ---> PASS

If else ---> FAIL

Script to transfere to cg_lims:  https://github.com/Clinical-Genomics/clinical_EPPs/blob/master/EPPs/calculate_amount_twist.py

-----------------------------------------------------------------------------------------------------------------------------
In the same steps but in the script "Get Volume Elution" (EPPs/get_volumes_from_buffer_twist.py). Samples that have gone through step "Buffer Exchange TWIST" will have a value in UDF "Volume Elution (ul)". The script will copy this value to UDF "Volume (ul)". It will leave the UDF "Volume (ul)" empty if a sample doesn't have a value.

Would it be possible to subtract 10 to this value? 
"Volume (ul)" = "Volume Elution (ul)" - 10

Script to transfer to cg_lims: https://github.com/Clinical-Genomics/clinical_EPPs/blob/master/EPPs/get_volumes_from_buffer_twist.py

**Comment by cesve** [comment]
@annagellerbring vill du dubbelkolla att jag fick alla QC-värden rätt? Det är så lätt att snurra till det...

**Comment by annagellerbring** [comment]
> @annagellerbring vill du dubbelkolla att jag fick alla QC-värden rätt? Det är så lätt att snurra till det...

I sammanfattningen skrev vi att conc skulle vara <250 ng/ul, ej <=. Vet inte om det var en tanke med det? Men vad jag ser så borde conc kunna vara 250ng/ul eftersom i denna "And if "Amount"/1 >= "Concentration" >= "Amount"/30 ---> PASS" så är Amount/1 **>=** Concentration.

**Comment by cesve** [comment]
> > @annagellerbring vill du dubbelkolla att jag fick alla QC-värden rätt? Det är så lätt att snurra till det...
> 
> I sammanfattningen skrev vi att conc skulle vara <250 ng/ul, ej <=. Vet inte om det var en tanke med det? Men vad jag ser så borde conc kunna vara 250ng/ul eftersom i denna "And if "Amount"/1 >= "Concentration" >= "Amount"/30 ---> PASS" så är Amount/1 **>=** Concentration.

Ja, jag tänker att den gränsen var pga att vi inte vill pipettera volymer lägre än 1 ul, och då kan ju konc vara 250 ng/ul.

**Comment by cesve** [comment]
@mayabrandi can you close this issue when it's in production? Thanks!
