### ISSUE TITLE
Import DIN-value from csv-file

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#196]
Lims Issue
---------------

**Work Flow:** Twist v3
**Protocol:** Initial QC TWIST v3
**Step:** Tapestation Reception Control TWIST

**Description:** We would like to import the DIN-values from a csv-file exported from TapeStation. The values should be imported to UDF "DIN Value".

**Comment by cesve** [comment]
@linnealafleur can you e-mail the csv-file from the Tapestation-computer to Maya? When this was done last time (when we implemented the import of sizes) I think the csv-file was first sent to a Mac-computer, downloaded and then forward to Maya. This caused some kind of errors when importing the sizes as the Mac did some changes in the file.

**Comment by linnealafleur** [comment]
@cesve @mayabrandi since the internet access for the tapestation computer is limited only to LIMS, I can not email directly from that computer. I tried send the file via the Kratos computer to Maya, so it has not passed a Mac computer. Please let me know if it dosn't work and I will try in an other way.

**Comment by mayabrandi** [comment]
example file

csv-file for DIN value

[rc200925tga-gDNA_sampleTable.csv.zip](https://github.com/Clinical-Genomics/clinical_EPPs/files/5821089/rc200925tga-gDNA_sampleTable.csv.zip)

**Comment by mayabrandi** [comment]
- [ ] add din file placeholder to step:

**Comment by mayabrandi** [comment]
The new script is now deployed to production
https://github.com/Clinical-Genomics/cg_lims/pull/23
