### ISSUE TITLE
New version of Development WF

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/clinical_EPPs#209]
**Workflow Name:** CG001 Development Projects

- [x] Add **Quantit step** to protocols _CG002 Library validation QC (Dev)_  and to CG002 _Initial QC (Dev)_. Can look like this: WF: WGS PCR free v4, protocol: Initial QC wgs v4 step: Quantit QC (DNA) WGS v1, but add button to calculate amount, remove button to set QC.
- [x] in **Qubit step** protocol **_Initial QC (Dev) v3_**
> add volume
> add buttoin to calculate amount
> show subbmitted sample lims id
- [x] in **Tapestation step**
> show lims id
> add button get size from file. (now it is on udf _Average size (bp)_. but should be on _Size (bp)_) In both  protocols _CG002 Library validation QC (Dev)_  and to CG002 _Initial QC (Dev)_
- [x] check that aggregate step is fine
- [x] **cg002 Libary Prep**
> show submitted sample lims id
- [ ] default sequencing should be **nova seq**
> make sure the correct number are being fetched to the define step

**Comment by cesve** [comment]
@Mropat kan vi titta på Tapestation steget? Jag skulle vilja ha en "sample placement" i steget.

**Comment by cesve** [comment]
@Mropat vi behöver också "Sample placement" i Quantit.

**Comment by cesve** [comment]
@Mropat placement map-scriptet körs men filen sparas inte i steget: https://clinical-lims-stage.scilifelab.se/clarity/work-details/173002

**Comment by cesve** [comment]
Test 210129. Steps where changes have been made are shown below:

***Protocol: Initial QC (Dev) v3***
_**Step: Tapestation Reception Control v3**_

**Comment by cesve** [comment]
Test 210129. Steps where changes have been made are shown below:

**_Protocol: Initial QC (Dev) v3
Step: Quantit QC (DNA) v1_**

- [x] Get concentration from file.
- [x] Placement map with *original well* and *original container*

**Comment by cesve** [comment]
Test 210129. Steps where changes have been made are shown below:

**_Protocol: Initial QC (Dev) v3
Step: Qubit QC (DNA) v3_**

- [x] UDF volume added in Sample Details.
- [x] Shows lims id in Sample Details.

![Uploading Screenshot 2021-01-29 at 13.25.27.png…]()

**Comment by cesve** [comment]
Test 210129. Steps where changes have been made are shown below:

**_Protocol: Initial QC (Dev) v3
Step: Aggregate QC (DNA) v3_**

Samples run in step **_Qubit QC (DNA) v3_**. Aggregation worked good.

<img width="671" alt="Screenshot 2021-01-29 at 13 28 20" src="https://user-images.githubusercontent.com/37171914/106275365-fea5ce80-6235-11eb-8358-c5b173006b29.png">

**Comment by cesve** [comment]
Test 210129. Steps where changes have been made are shown below:

**_Protocol: Library validation QC (Dev) v3
Step: Quantit QC (DNA) v1_**

- [x] Get concentration from file.
- [x] Placement map with source well and source container

Everything work as expected. Samples get their concentrations and Placement map is generated correctly, see pictures. The csv-file is found in this [step](https://clinical-lims-stage.scilifelab.se/clarity/work-details/173036)

![Screenshot 2021-01-29 at 15 00 04](https://user-images.githubusercontent.com/37171914/106284129-15065700-6243-11eb-973b-43e8c1b4a614.png)

![Screenshot 2021-01-29 at 15 03 14](https://user-images.githubusercontent.com/37171914/106284174-23ed0980-6243-11eb-867c-aef6168ecfd1.png)

The "Calculate amount" script is verified in another issue.

**Comment by cesve** [comment]
est 210129. Steps where changes have been made are shown below:

**_Protocol: Library validation QC (Dev) v3
Step: Tapestation QC v3_**

- [x] Shows lims id in Sample Details.
- [x] Added script to get Size (bp) from csv-file.
- [x] Added UDF "Size (bp) in Sample Details.

Everything work as expected. Samples get their sizes, see picture. The csv-file is found in this: [step](https://clinical-lims-stage.scilifelab.se/clarity/work-complete/173034)

![Screenshot 2021-01-29 at 15 57 15](https://user-images.githubusercontent.com/37171914/106290625-f99f4a00-624a-11eb-96d1-cba01021b248.png)

**Comment by cesve** [comment]
Test 210129. Steps where changes have been made are shown below:

Protocol: Initial QC (Dev) v3
Step: Aggregate QC (DNA) v3

Samples run in step Qubit QC (DNA) v3. Aggregation worked good.

![Screenshot 2021-01-29 at 15 57 15](https://user-images.githubusercontent.com/37171914/106293851-c068d900-624e-11eb-9d51-4af3c2f4b887.png)

**Comment by Mropat** [comment]
Concentration copied successfully into files!
![image](https://user-images.githubusercontent.com/35531751/106295805-2eae9b00-6251-11eb-9fd7-7217445f3fde.png)
