### ISSUE TITLE
script giving error even though it works

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#210]
This is the script:
https://github.com/Clinical-Genomics/clinical_EPPs/blob/master/EPPs/aggregate_QC_n_copy_fields.py
This is the error:
![Screenshot 2021-01-28 at 16 58 58](https://user-images.githubusercontent.com/37171914/106164469-4838df80-618a-11eb-86ab-dade7b4e18c5.png)

**Comment by mayabrandi** [comment]
The step had hidden master step udfs that were read by the script. Had to set the udfs to none to get rid of the warning message. A better solution would have been top make a new version of the step wit only udfs that are being used. But we don't have time for that now , so making a quick and ugly..
