### ISSUE TITLE
Import UDF "Volume (uL)" TWIST v3

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#212]
Lims Issue
---------------

**Work Flow:** TWIST v3
**Protocol:** **_Initial QC TWIST _v3__** and **_Initial QC TWIST v3_**
**Step:** **_Buffer Exchange TWIST_** and **_Qubit QC (DNA) TWIST_** and _**Quantit QC (DNA) TWIST**_

**Description:** We have updated the ordering process so that the customer now has to specify volume. The UDF in the orderform is named "Volume (uL)". We would like to import this value to the steps specified above. It should be imported to UDF "Volume (ul)" but as Measurement (not submitted sample).

**_Note:_** In this wf in steps **_Qubit QC (DNA) TWIST_** and _**Quantit QC (DNA) TWIST**_ we have a script that says "**_if_** sample has been through step **_Buffer Exchange TWIST_** "Volume (uL) = "Volume Elution (ul)". The button is named 0. Get Volume Elution". We still want that script! So, if samples have _**not**_ been through step **_Buffer Exchange TWIST_** then Volume (ul) should be imported from the orderform. But if they've been through the step, then "Volume (ul)"= "Volume Elution (ul)". Does this make sense?

**Comment by cesve** [comment]
@Mropat and @mayabrandi this issue is almost the same as #211 

It's not super urgent but this issue is the most prioritised of the Prep lab related issues in this repo and will help us in the lab a lot. Let me know when you'll have time to work on it. We can have a meeting and I can explain it a bit more.

Thanks!

**Comment by mayabrandi** [comment]
There is a script in place so all that’s needed is to set the configurations. You want to give it a try Cissi? 

Skickat från min iPhone

**Comment by cesve** [comment]
Just noticed:

In step **_Buffer Exchange TWIST_** the UDF _Volume (uL)_ needs to be imported to UDF _Sample Volume (ul)_ not to UDF _Volume (ul)_. Or another suggestion is to change the calculation script in this step so that the calculations are based on UDF

 @mayabrandi

**Comment by cesve** [comment]
Would it be very complicated to remove the "0" from button _0. Get Volume Elution_? @mayabrandi 

When we added this new button you must run that button before running _0. Get Volume Elution_ otherwise the volumes will be wrong.

**Comment by cesve** [comment]
The volume was successfully imported. In this step **_Buffer Exchange TWIST_** the UDF _Volume (uL)_ was imported to UDF _Sample Volume (ul)_.

![Screenshot 2021-02-10 at 11 37 47](https://user-images.githubusercontent.com/37171914/107498718-70660c80-6b94-11eb-98b3-0312baacf4a8.png)
