### ISSUE TITLE
archive EPP aliquot_covaris_microbial.py

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/clinical_EPPs#217]
Lims Issue
---------------

**Work Flow:** tbd
**Protocol:** tbd
**Step:** tbd

**Description:** Archive EPP `aliquot_covaris_microbial.py`. See https://github.com/Clinical-Genomics/cg_lims/issues/86

**Comment by mayabrandi** [comment]
closing issue because script is still in use and should not be archived. see https://github.com/Clinical-Genomics/cg_lims/issues/86
