### ISSUE TITLE
Twist prover får ingen conc i Novaseq 1

### ISSUE THREAD

**Issue by AnnaZetterlund** [Clinical-Genomics/clinical_EPPs#67]
Lims Issue
---------------

**Work Flow:** NovaSeq 1
**Protocol:** Define Run Format and Calculate Volumes (Nova Seq)
**Step:** Record Details

**Description:** När man hämtar konc så hämtas inte konc från twist flödet.

**Comment by mayabrandi** [comment]
Fixade vi inte detta?? 

Jag tar en titt på det.

Har du nåt öppet steg jag kan kika på?

/M

**Comment by mayabrandi** [comment]
fixed
