### ISSUE TITLE
Plattan sorterad på fel håll...

### ISSUE THREAD

**Issue by AnnaZetterlund** [Clinical-Genomics/clinical_EPPs#68]
Lims Issue
---------------

**Work Flow:** Novaseq 1
**Protocol:** Define Run Format and Calculate Volumes (Nova Seq)
**Step:** Queue

**Description:** I queue så är plattan sorterad efter bokstav så proverna ligger A1, A2, A3... Jag skulle vilja ha dem A1, B1, C1...
Tack!

**Comment by AnnaZetterlund** [comment]
https://clinical-lims.scilifelab.se/clarity/work-details/107252

**Comment by mayabrandi** [comment]
Har ändrat well sort order, från row till column. Kolla om det är rätt nu så stänger vi denna issue sen

**Comment by AnnaZetterlund** [comment]
Ser fint ut!
