### ISSUE TITLE
Wrong water volume calculated 

### ISSUE THREAD

**Issue by keyvanelhami** [Clinical-Genomics/clinical_EPPs#75]
Lims Issue
---------------

**Work Flow:** CG002 - Plate Setup MAF
**Protocol:** CG002 - Plate Setup MAF
**Step:** Here to!

**Description:** The volume water are calculated wrongly when the concentration is too high for the samples. I believe that the calculation is wrong when the volume is below 1ul for samples (see screen shot). Or is this due to the high concentration and the total volume is 50ul insteaD?
<img width="1212" alt="Screenshot 2019-05-20 at 14 38 08" src="https://user-images.githubusercontent.com/26735714/58022112-ff074000-7b0c-11e9-833c-3923f1cc1507.png">

**Comment by mayabrandi** [comment]
The script is set up like this:

If sample volume is < 0.5 the the final volume is set to 50.

Is that okey? 

/Maya


> 20 maj 2019 kl. 14:39 skrev keyvanelhami <notifications@github.com>:
> 
> CG002 - Plate Setup MAF

**Comment by keyvanelhami** [comment]
Yes that is ok!
