### ISSUE TITLE
New criteria for RC in microbial WF

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#80]
Lims Issue
---------------

**Work Flow:** CG002 Microbial WGS
**Protocol:** CG002 Initial QC Microbial
**Step:** CG002 - Quantit QC (DNA)

**Description:** We want to change the approved concentrations from 2-50 to 1-50. The approved concentrations for samples named NTC* should not be change.

**Comment by mayabrandi** [comment]
Done!
