### ISSUE TITLE
Add a method in two normalization steps (micro)

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#81]
Lims Issue
---------------

**Work Flow:** CG002 Microbial WGS
**Protocol:** "CG003 - Nextera Microbial WGS" and "CG002 - Normalization of microbial samples for sequencing"
**Step:** "CG002 - Normalization of microbial samples" and "CG002 - Normalization of microbial samples for sequencing"

**Description:** In the "Method" dropdown list we want to add "manually" as a choice. The method version no should not be required.

**Comment by mayabrandi** [comment]
Done!
