### ISSUE TITLE
Add a warning in calculation script (micro)

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#82]
Lims Issue
---------------

**Work Flow:** CG002 Microbial WGS
**Protocol:** CG002 - Normalization of microbial samples for sequencing
**Step:** CG002 - Normalization of microbial samples for sequencing

**Description:** We want the script to give a warning if the total volume is below 10 ul.

**Comment by mayabrandi** [comment]
Do you mean the qc-flagg for the sample with low total volume should be red?

**Comment by cesve** [comment]
Yes!

**Comment by mayabrandi** [comment]
Done!
