### ISSUE TITLE
Change text for kit (micro)

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#83]
Lims Issue
---------------

**Work Flow:** CG002 Microbial WGS
**Protocol:** CG003 - Nextera Microbial WGS
**Step:** CG002 - Microbial Library Prep (Nextera)

**Description:** We want to change the field "Lot nr: Library prep kit" to "Lot nr: Tagmentation buffer (TD-buffer)" and also add a field "Lot nr: Tagmentation enzyme (TDE1)".

**Comment by mayabrandi** [comment]
@ingkebil @patrikgrenfeldt @emiliaol can we change this step udf safely without affecting cg? I searched the udf in cg repo but didnt find anything so it seems safe, but I want to ask you anyway.

**Comment by mayabrandi** [comment]
@cesve  Should "Lot nr: Tagmentation enzyme (TDE1)" be a Text field? Should it be requiered?

**Comment by cesve** [comment]
Yes, a text field for both. And yes, required.

**Comment by ingkebil** [comment]
It looks fine to change this UDF. Go ahead!

**Comment by mayabrandi** [comment]
👍

**Comment by cesve** [comment]
Hej Maya, vi upptäckte att fältet  "Lot nr: Tagmentation enzyme (TDE1)" saknas. 
Det finns endast "Lot nr: Tagmentation buffer (TD-buffer)" men vi vill ha alltså ha 2 st fält.

**Comment by mayabrandi** [comment]
Sorry. Nu ligger den uppe
