### ISSUE TITLE
Updates for CG003 - Nextera Microbial WGS protocol

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#84]
Lims Issue
---------------

**Work Flow:** CG002 Microbial WGS
**Protocol:** CG003 - Nextera Microbial WGS
**Step:** CG002 - Microbial Library Prep (Nextera), CG002 - Quantit QC (normalization)

**Description:** 
We would like to remove the step "CG002 - Quantit QC (normalization)"
And the step "CG002 - Microbial Library Prep (Nextera)" should be divide into two. 

The first step should be named as it is today and include:
- "Place samples" (as it is now, no changes)
- "Add labels" (as it is now, no changes)
- "Next steps" with following fields (no changes): 
"Method"
"Method version"
"Tagmentation buffer (TD-buffer)" with free text
"Tagmentation enzyme (TDE1)" with free text
"Lot nr: Index"
"Lot nr: KAPA HiFi HotStart ReadyMix (2X)"
"PCR-instrument incubation".

The Placement map script should also be here.

The new step can be named "post-PCR bead purification" and include:
- "Place samples - 96 well, tube"
- "Next steps" with following fields: 
"PCR instrument amplification",  - drop down som ovan,
"Nr PCR cycles",  fri
"Lot nr: EtOH",  fri
"Lot nr: Beads",  fri
"Lot nr: H2O". fri

**Comment by cesve** [comment]
**Test Specification planned by MB 190910**

**Comment by cesve** [comment]
**Implementation:** 
Steps to fix when putting into produciton:

- [ ] update script settings in initial qc. Both WF and Prot. See screen shot

- [ ] update script settings for make placement map according to screen shot below. When running script according to screen shot, the source containeris taken from the previous step. But, the container name was not shown in the placement map. This needs to be fixed before put into production.

**Comment by mayabrandi** [comment]
**Conclusion**

The new updates of the microbial workflow has been tested on stage, and the new version has been copied into production and is ready to be used. 

I will mail the information to everyone concerned.

/MB
