### ISSUE TITLE
Add a step for bead-purification in Initial QC protocol

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#85]
Lims Issue
---------------

**Work Flow:**  "CG002 Microbial WGS" and "Twist v1"
**Protocol:** "CG002 Initial QC Microbial" and "Initial QC TWIST v1"
**Step:** New step in these protocol, can be named: "Buffer exchange"

**Description:** A new step with following details:

- Place Samples
- Next Steps: fields with "Lot Nr: EtOH", "Lot Nr: Nuclease-free water", "Lot Nr: Purification Beads", "Method document" and "Document version".

**Comment by mayabrandi** [comment]
Now in place!

**Comment by cesve** [comment]
I noticed that step: "Aliquot samples for enzymatic fragmentation TWIST" in protocol: "Initial QC TWIST v1" in Work flow: Twist v1 doesn't pick up the new sample placement if the sample has been buffer exchanged. In the step they still have the original container name and placement. They should have the new container name and placement, the one they were given in the Buffer exchange step.

**Comment by mayabrandi** [comment]
This one should be solved now. I updated so that the source well in the placement map is the well from previous step, and not the original well. Let me know if the problem occurs again
