### ISSUE TITLE
Add a Quant-iT and Tapestation step in Initial QC protocol

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#86]
Lims Issue
---------------

**Work Flow:** CG003 WGS PCR free
**Protocol:** CG002 Initial QC and CG002 Library validation QC
**Step:** New step, can be named: "Tapestation Reception Control" for TapeStation and "Quantit QC (DNA)" for Quant-iT.

**Description:** 

1. TapeStation: Add a Tapestation step similar to the one used in Twist v2 with following information:

- Next steps with following fields: "Method document", "Document version", "Assay", "Lot no kit" and "Comment" (free text). Also the possibility to attach two Tapestation Files (one pdf report and one csv file) and set average size etc. The same as the step in Twist v2, step "Tapestation Reception Control TWIST" (which should also be updated in some respects).

2. Quant-iT QC: Add a step similiar to the one in used in protocol "Initial QC TWIST v2" step "Quantit QC (DNA) TWIST".

Default should always be placement in 96-well plate and column as placement method (not pattern or rows).

We need a placement step (into a 96-well plate). We need to be able to upload an excel-file and allocate the concentrations to the right well. We would also need a set QC-script, which would be the same as the one in protocol CG002 - Qubit QC (DNA). It would also be nice to have a placement map with lims id, sample id, project name, original container and original well position.

Where ever it is possible (Ice bucket, queue etc) we want the following information: lims id, sample id, project name, original container and original well position.

**Comment by cesve** [comment]
In the same protocol we would like to add a Quant-iT step.

**Comment by cesve** [comment]
@annaengstrom har jag missat något? Visst kan man ladda upp en excelfil i TWIST-steget också (Quant-it)? Sätter man QC i detta steg i TWIST?

**Comment by annaengstrom** [comment]
@cesve jag har ändrat några småsaker. Nej man kan inte nu ladda upp csv fil i Twist men vi att det ska vara så.

**Comment by cesve** [comment]
@mayabrandi Kan du kolla på två grejer:

I Initial QC wgs v3, Step 1. Quantit QC (DNA) WGS v1:
Kan vi lägga till en placement map med info: sample name, lims id (submitted sample), project no, original container och original well?

I Library validation QC wgs v3, Step 2. Quantit QC (DNA) WGS v1**: kan vi ta bort pre-set uppe i högra hörnet och ändra Quality criteria till conc > 1 ng/ul?

Det var de grejerna jag ville ändra innan vi kan utföra testet.

Jag är tillbaka mån 4/11 igen!

**Comment by mayabrandi** [comment]
Yes!

**Comment by mayabrandi** [comment]
> I Initial QC wgs v3, Step 1. Quantit QC (DNA) WGS v1:
> Kan vi lägga till en placement map med info: sample name, lims id (submitted sample), project no, original container och original well?
> 

Yes. Last till. Kolla gärna.

> I Library validation QC wgs v3, Step 2. Quantit QC (DNA) WGS v1**: kan vi ta bort pre-set uppe i högra hörnet och ändra Quality criteria till conc > 1 ng/ul?
> 
Tror vi måste snacka om detta irl så det inte blir fel. Kommer vara snabbt fixat.

**Comment by cesve** [comment]
Done and implemented!
