### ISSUE TITLE
Add UDF for bait set used in the lab in Twist workflow

### ISSUE THREAD

**Issue by annaengstrom** [Clinical-Genomics/clinical_EPPs#91]
Lims Issue
---------------

**Work Flow:** Twist v1
**Protocol:** Target Enrichment Twist v1
**Step:** Hybridize library Twist

**Description:** 
Targeted genome analysis (TGA) samples are currently ordered either with app tag EXO or PAN, and customer specifies which "lab" panel (= bait set) to use in the lab. They are free text fields and specified on the website: https://clinical.scilifelab.se/requirements under "Bait sets". This information is not enough to connect the bed file to the sample as the panels will evolve and have different versions. We do not want to make the choices so specific for the cutomers, that is why the bait sets on the website will fairly rarely change, but might change more often in the lab + lims. 

Specifically, the actual bait set used in the lab (in Lims Step Hybridize library Twist) must be documented in such a way that MIP and BALSAMIC can fetch this information so that the correct bed file is used for each sample.

For each sample we need to be able add information on a sample level - UDF? - with a limited selection of pre-sets (will change from time to time but not so often - estimation: a few times a year). 

Examples of pre-sets:

Twist Human core exome v1.3
Twist Human core exome v1.3 + Twist Human RefSeq Panel
LymphoMATIC2.1
GIcfDNA3.1
GMCKSolid4.1
GMSmyeloid5.1

Information taken from: https://docs.google.com/spreadsheets/d/1Zvp6DZMgOfpoLsGKWRD9iQ_6iAh0BYhmP5xsK5SJxIM/edit#gid=0
this is where bait set information is kept before implementing a database

**Comment by annaengstrom** [comment]
@annagellerbring @vwirta FYI
@henrikstranneheim @hassanfa FYI
@emiliaol FYI

**Comment by annaengstrom** [comment]
@ingkebil FYI

**Comment by annaengstrom** [comment]
@ingkebil @henrikstranneheim @hassanfa Do we already now have to discuss how MIP and BALSAMIC communicate with Lims?

**Comment by hassanfa** [comment]
I don't know how that BALSAMIC can communicate with LIMS. There is another discussion on how this might be implemented in clinical-db: https://github.com/Clinical-Genomics/cg/issues/358 .

Unless our core packages know about bed files, BALSAMIC won't know either. I am strongly against connecting workflows to LIMS, or at least BALSAMIC.

**Comment by henrikstranneheim** [comment]
I do not think any workflow should know anything about LIMS. Each workflow should as stand alone as possible. 

Cg should fetch the correct bed file version and place it correctly in the workflow API. 

For MIP: Any LIMS info should either be added to the CLI, config, or pedigree file in a supported format. Usually for capture kits the info is placed in the pedigree on sample level, however it can be placed in any of these three places.

**Comment by annaengstrom** [comment]
Thanks for your comments @hassanfa @henrikstranneheim. As of next week (24 June 2019) we are starting using spike in bait sets for TGA samples. 

Who should take responsibility to bring information from Lims to MIP and BALSAMIC in an appropriate way? TTN?


@emiliaol How should we communicate to the bioinformatics production team which bait sets have been used for each sample? We have the information manually written under the step Hybridization in the Twist work flow currently. Do you have the new bed file for the RefSeq panel (new addition to the exome? @keyvanelhami)

**Comment by mayabrandi** [comment]
A new analyte udf (derived sample) is added. Its called "Bait Set". The output artifacts of the "Hybridize library Twist" step will contain this udf. (it is not set as requiered though. Should it be?? @annaengstrom ) There is one output artifact per pool, but all samples in one pool will have the same bait set. Cg developers, please let me know if you need help in fetching the udf.

**Comment by annaengstrom** [comment]
@mayabrandi Thanks! It should be required.

**Comment by mayabrandi** [comment]
Ok. Is "Bait Set" a proper name for the udf?

> 24 juni 2019 kl. 10:50 skrev Anna Engström <notifications@github.com>:
> 
> should

**Comment by annaengstrom** [comment]
"Bait set" is good

**Comment by mayabrandi** [comment]
Can I close this issue now? @annaengstrom

**Comment by annaengstrom** [comment]
Yes
