### ISSUE TITLE
Change QC for negative controls (NTC)

### ISSUE THREAD

**Issue by cesve** [Clinical-Genomics/clinical_EPPs#96]
Lims Issue
---------------

**Work Flow:** Microbial WGS v4
**Protocol:** CG002 - Microbial Library Validation QC
**Step:** CG002 - Aggregate QC (Library Validation)

**Description:** Change the criteria for negative controls **NTC** to fail if concentration is >=1 (större eller lika med).

**Comment by mayabrandi** [comment]
done
