### ISSUE TITLE
NovaSeq v2

### ISSUE THREAD

**Issue by AnnaZetterlund** [Clinical-Genomics/clinical_EPPs#97]
Lims Issue
---------------

**Work Flow:** NovaSeq v2
**Protocol:** Define Run Format and Calculate Volumes och Record details. 
**Step:** Queue

**Description:** 

- [x] Microbiella prov som köats om hit ska ligga i platta men låg i tube.
- [x] Microbiella prov som köats om hit hade bara lims namn och inte vårt plattnamn.
- [x] Proverna är sorterade på fel håll i Queue. Vill att det går vågrätt och inte horisontellt. 
- [x] Jag skulle vilja ha proverna uppdelade på platta i Record detail steget och inte som nu i en lång lista. Vill gärna ha brunnsposition också. 
- [x] I record details steget så hade det varit fint om det visades en summa av Reads to sequence (M). Så har det varit i X och 2500. Bra check att se att man inte tänkt helt fel. När man trycker på knappen get reads to sequence

**Comment by mayabrandi** [comment]
yes!

**Comment by AnnaZetterlund** [comment]
Vi kan titta på detta tillsammans imorgon om du vill! Är du inne då?

**Comment by mayabrandi** [comment]
Yes! Det gör vi!

**Comment by mayabrandi** [comment]
👍
